# Generated by Django 3.1.5 on 2021-02-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='phone')),
                ('message', models.TextField(blank=True, verbose_name='message')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Phone Company')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Company')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Company address')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Temalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Tema')),
                ('content', models.TextField(blank=True, verbose_name='message')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image')),
            ],
        ),
    ]
