# Generated by Django 3.1.7 on 2021-03-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reshebnik_app', '0002_auto_20210306_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformus',
            old_name='fan',
            new_name='avatar',
        ),
    ]
