# Generated by Django 3.1.7 on 2021-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reshebnik_app', '0003_auto_20210306_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformus',
            name='avatar',
            field=models.CharField(max_length=100, verbose_name='Fan'),
        ),
    ]
