# Generated by Django 3.1.7 on 2021-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reshebnik_app', '0008_auto_20210319_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otziv',
            name='point_ru',
        ),
        migrations.AddField(
            model_name='otziv',
            name='status_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Cтатус'),
        ),
    ]
